### PR TITLE
fix: Ensures directory path to db file exists

### LINKED ISSUE #122: Error when following getting started guide
Hi, I am starting my experiments with Temporal and the getting started docs resulted in an error for me.

Temporal started normally when I pre-created the missing directory, but Temporal should probably either create it, or the docs should mention it is needed

```
mkdir -p /home/vpavlin/.config/temporalite/db
```

## Expected Behavior

```
$ /home/vpavlin/devel/bin/temporalite start --namespace default
{"level":"info","ts":"2022-09-05T08:29:27.156+0200","msg":"Successfully saved cluster metadata.","component":"metadata-initializer","cluster-name":"active","logging-call-at":"fx.go:631"}
```

## Actual Behavior

```
$ /home/vpavlin/devel/bin/temporalite start --namespace default
2022/09/05 08:27:57 error setting up schema: stat /home/vpavlin/.config/temporalite/db: no such file or directory
```

## Steps to Reproduce the Problem

1. `go install github.com/temporalio/temporalite/cmd/temporalite@latest`
1. ` temporalite start --namespace default`

## Specifications

- Version:
- Platform:

### PR DESCRIPTION
**Pull request by hferentschik**
fixes #122

### CODE REVIEW

File: cmd/temporalite/main.go [hunk 1]
```diff
@@ -155,6 +157,11 @@ func buildCLI() *cli.App {
 					return cli.Exit(fmt.Sprintf("ERROR: only one of %q or %q flags may be passed at a time", ephemeralFlag, dbPathFlag), 1)
 				}
 
+				err := ensureDirExists(filepath.Dir(c.String(dbPathFlag)))
```
Comment (jlegrone) [inline cmd/temporalite/main.go:160]: I'm of mixed opinions about whether we should automatically create _any_ directory, or only do this when falling back to the default path in the user's home directory. See also https://github.com/temporalio/temporalite/issues/55#issuecomment-1118193801

Comment (cretz) [inline cmd/temporalite/main.go:160]:
```suggestion
				err := os.MkdirAll(filepath.Dir(c.String(dbPathFlag)), os.ModePerm)
```

You basically just rewrote what `MkdirAll` already does in your function

Comment (cretz) [reply cmd/temporalite/main.go:160]: I'm not too concerned about it for this type of utility. I have multiple notes here:

* If you are concerned, you can default the DB to the current working dir, but sadly that'd be a compatibility change at this point
* If it would make you feel better, you can only lazily create the path when using the default
* If it's clearly logged the path of DB that is being used on program start, I think that's good enough
* Alternatively, we could just not have a default DB path at all

Comment (hferentschik) [reply cmd/temporalite/main.go]: LOL, you are right. I updated the PR.

Comment (hferentschik) [reply cmd/temporalite/main.go]: I am not concerned about it in this case. For the default case, it makes sense. In the case the user specifies the path explicitly, I would expect it to exist in most cases. If not, the user gets, in the worst case, a directory created at an unexpected location which he can move or delete.

**Review by cretz — APPROVED** [review]
Approved, but would like @jlegrone's approval before merging

File: cmd/temporalite/main.go (hunk 1 above)
Comment (jlegrone) [reply cmd/temporalite/main.go]: > the user gets, in the worst case, a directory created at an unexpected location which he can move or delete.

I think the _worst_ case is that someone manages to mangle the flag in a production server, and Temporalite starts up without issue but now with a fresh database. It could be non-obvious at first since the server is healthy, but old data is missing. At that point you could have two separate databases with prod data that can't easily be merged.

> If it would make you feel better, you can only lazily create the path when using the default

This is what I was suggesting... but I'm probably being overly conservative.

Comment (cretz) [reply cmd/temporalite/main.go]: I'd support that. @hferentschik - think you can change to only `MkdirAll` if the user didn't specify a value explicitly?

Comment (jlegrone) [reply cmd/temporalite/main.go]: Yeah looking around, I think you might be hard pressed to find other databases that behave this way. Let's fix the getting started instructions and reconsider other cases if we get further user feedback.

File: cmd/temporalite/main.go [hunk 2]
```diff
@@ -162,6 +163,11 @@ func buildCLI() *cli.App {
 					return cli.Exit(fmt.Sprintf("ERROR: only one of %q or %q flags may be passed at a time", ephemeralFlag, dbPathFlag), 1)
 				}
 
+				err := os.MkdirAll(filepath.Dir(c.String(dbPathFlag)), os.ModePerm)
+				if err != nil {
```
Comment (jlegrone) [inline cmd/temporalite/main.go:167]: small nit

```suggestion
				if err := os.MkdirAll(filepath.Dir(c.String(dbPathFlag)), os.ModePerm); err != nil {
```

File: cmd/temporalite/main.go [hunk 3]
```diff
@@ -162,6 +163,10 @@ func buildCLI() *cli.App {
 					return cli.Exit(fmt.Sprintf("ERROR: only one of %q or %q flags may be passed at a time", ephemeralFlag, dbPathFlag), 1)
 				}
 
+				if err := os.MkdirAll(filepath.Dir(c.String(dbPathFlag)), os.ModePerm); err != nil {
```
Comment (cretz) [inline cmd/temporalite/main.go:166]: I think we only want to do this when the user didn't provide their own path

**Review by cretz — CHANGES_REQUESTED** [review]

File: cmd/temporalite/main.go (hunk 3 above)
Comment (hferentschik) [reply cmd/temporalite/main.go]: Done

**Review by jlegrone — APPROVED** [review]

File: cmd/temporalite/main.go [hunk 4]
```diff
@@ -162,6 +163,13 @@ func buildCLI() *cli.App {
 					return cli.Exit(fmt.Sprintf("ERROR: only one of %q or %q flags may be passed at a time", ephemeralFlag, dbPathFlag), 1)
 				}
 
+				// Make sure the default db path exists (user does not specify path explicitly)
+				if !c.IsSet(dbPathFlag) {
```
Comment (cretz) [inline cmd/temporalite/main.go:167]: Can you confirm this is not considered "set" when left as default?

**Review by cretz — APPROVED** [review]

File: cmd/temporalite/main.go (hunk 4 above)
Comment (jlegrone) [reply cmd/temporalite/main.go:173]: Yes this leads to the correct behavior. I'd like to add an integration test though.
